app = "deepdata"  # Replace with your preferred app name

[build]
  [build.args]
    build_phase = "true"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  
  [[http_service.checks]]
    interval = "10s"
    timeout = "2s"
    path = "/"